apiVersion: apps/v1
kind: DaemonSet
metadata:  
  name: example-daemonset
spec:  
  selector:    
    matchLabels:      
      name: example-daemonset  
  template:    
    metadata:      
      labels:        
        name: example-daemonset    
    spec:      
      terminationGracePeriodSeconds: 60      
      containers:      
      - name: example-container        
        image: mcr.microsoft.com/oss/kubernetes/pause:3.6       
        lifecycle:          
          preStop:            
            exec:              
              command: ["/bin/sh", "-c", "echo 'Gracefully terminating...' && sleep 30"]
        resources:
          requests:
            cpu: "800m"
            memory: "2000Mi"
          limits:
            cpu: "1000m"
            memory: "2000Mi"
